spring:
  datasource:
    initialization-mode: always
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:licenta}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_USERNAME:cataclysm91}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO:create}
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID:5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com}
            clientSecret: ${GOOGLE_CLIENT_SECRET:tWZKVLxaD_ARWsriiiUFYoIk}
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: ${MAX_FILE_TRESHOLD:300MB}
      max-request-size: ${MAX_REQUEST_SIZE:300MB}

app:
  auth:
    tokenSecret: ${TOKEN_SECRET:926D96C90030DD58429D2751AC1BDBBC}
    tokenExpirationMsec: 3600000
  oauth2:

    authorizedRedirectUris:
      - ${REDIRECT_URI_01:http://localhost:3000/oauth2/redirect}
file:
  upload-dir: users

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder : TRACE

core:
  root: ${DS_CORE_ROOT:localhost:8000/api/core/}

init:
  userpass: ${INIT_USERPASS:parola}