POST {{local_url}}/core/hw_forecast?data_set_id=2
Accept: application/json
Authorization: Bearer {{temp_token}}
Content-Type: application/json

{
  "y" : "Thousands of Passengers",
  "freq" : "Month",
  "periods": 36,
  "model" : "mul",
  "train_percent" : 80
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}
###