GET localhost:8080/dataset/downloadDataSetFile/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNTg1MjUyMTEwLCJleHAiOjE1ODYxMTYxMTB9.gb84aC7DuhsH4ThnZ5Tbs6LtniNSocE1gY5_jFc-SJBNbxC-r8sX0IvVoBWIdmwoqJuD7e5IwWiCxr_ewM0NRw
Accept: application/json
Content-Type: application/json
###
