GET localhost:8080/dataset/get_datasets
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTg1NTcxMDA4LCJleHAiOjE1ODY0MzUwMDh9.97pXTPzsRi_I5UQAZt_yR_0poIhk4bJZ1qvwnHuggNdgIW7ZppU0xB8sDsfWxg6CnSzRKtJG9hhT611rs7xZ1A
Accept: application/json
Content-Type: application/json
###