GET http://localhost:8080/user/me
Accept: application/json
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNTg1MjQ5NjYyLCJleHAiOjE1ODYxMTM2NjJ9.SrI7p5pMdl_5bz_p6nS8lIx1IYrOF5UjLaEb_YWvmpjfR4p8pFbF_pZB7hQSCCOe0XLPhGVDIU7gJClgDZ7tRg
###
